site_name: Wave wet en regelgeving

theme:
  name: material
  langueage: en
 
# Copyright
copyright: Copyright &copy; 2023 - 2024 Sunstone

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Kamer van Koophandel: bedrijven.md
  - Gebieden: risico-gebieden.md
  - Kosten:
    - Advocatuur: kosten/advocaat.md
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Impound: kosten/inbeslagname.md
