site_name: Sunstone wet en regelgeving

theme:
  name: material
 
# Copyright
copyright: Copyright &copy; 2023 - 2024 Sunstone

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
 
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Algemene Plaatselijke Verordening TS: apvts.md
  - Wetboek: wetboek.md
  - Kamer van Koophandel: bedrijven.md
  - Gebieden: risico-gebieden.md
  - Kosten:
    - Advocatuur: kosten/advocaat.md
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Impound: kosten/inbeslagname.md
